import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as THREE from 'three';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ArrowRight, Phone, MapPin, Wrench, Gauge, ShieldCheck, BatteryCharging, CarFront, Menu, X, CheckCircle2, Clock3, Sparkles} from 'lucide-react';
import './styles.css';

gsap.registerPlugin(ScrollTrigger);

const services=[
 ['Engine Diagnostics','Computer scanning, fault tracing and accurate engine health checks.',Gauge],
 ['Oil Change & Maintenance','Quality oil service, filters, fluids and preventive maintenance.',Wrench],
 ['Catalytic Converter Service','Inspection, cleaning and troubleshooting for exhaust performance.',CarFront],
 ['Suspension & Steering Check','Brake, suspension, wheel and steering safety inspection.',ShieldCheck],
 ['Battery Inspection','Battery health, charging system and starting diagnostics.',BatteryCharging],
 ['Engine Overhauling','Detailed engine repair and overhaul work with careful inspection.',Wrench],
 ['Throttle Body Cleaning','Restore smoother throttle response and better idle performance.',Gauge],
 ['Injector Cleaning','Fuel injector cleaning for efficient combustion and performance.',Sparkles],
 ['Spark Plug Cleaning','Inspection and cleaning to support reliable ignition.',Sparkles],
 ['4-Wheel Brake Service','Brake inspection, cleaning and maintenance for confident stopping.',ShieldCheck]
];

function ThreeHero(){const ref=useRef(); useEffect(()=>{const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100);camera.position.z=6;const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);ref.current.appendChild(renderer.domElement);const geo=new THREE.IcosahedronGeometry(2.2,1);const mat=new THREE.MeshBasicMaterial({color:0x1f9d68,wireframe:true,transparent:true,opacity:.16});const mesh=new THREE.Mesh(geo,mat);scene.add(mesh);const pts=new THREE.BufferGeometry();const arr=new Float32Array(450);for(let i=0;i<arr.length;i++)arr[i]=(Math.random()-.5)*14;pts.setAttribute('position',new THREE.BufferAttribute(arr,3));const pm=new THREE.PointsMaterial({color:0xe7b94d,size:.025,transparent:true,opacity:.7});scene.add(new THREE.Points(pts,pm));let frame;const animate=()=>{mesh.rotation.x+=.0008;mesh.rotation.y+=.0015;renderer.render(scene,camera);frame=requestAnimationFrame(animate)};animate();const resize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)};addEventListener('resize',resize);return()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize);renderer.dispose();ref.current?.removeChild(renderer.domElement)}},[]);return <div className="three" ref={ref}/>}

function App(){const [open,setOpen]=useState(false);const root=useRef();useEffect(()=>{gsap.fromTo('.hero-copy > *',{y:35,opacity:0},{y:0,opacity:1,duration:1,stagger:.12,ease:'power3.out'});gsap.utils.toArray('.reveal').forEach(el=>gsap.fromTo(el,{y:45,opacity:0},{y:0,opacity:1,duration:.8,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 84%'}}));return()=>ScrollTrigger.getAll().forEach(t=>t.kill())},[]);
const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setOpen(false)};
return <div ref={root}>
<header className="nav"><div className="brand" onClick={()=>go('home')}><span>CH</span><div><b>CH AUTO</b><small>WORKSHOP</small></div></div><button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'show':''}><button onClick={()=>go('home')}>Home</button><button onClick={()=>go('services')}>Services</button><button onClick={()=>go('about')}>About</button><button onClick={()=>go('why')}>Why Us</button><button onClick={()=>go('gallery')}>Workshop</button><button className="nav-cta" onClick={()=>go('contact')}>Contact <ArrowRight size={16}/></button></nav></header>
<section id="home" className="hero"><ThreeHero/><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow">SAHIWAL • PAKISTAN <span>EST. AUTO CARE</span></div><h1>Built for the road.<br/><em>Trusted by drivers.</em></h1><p>Modern diagnostics, honest maintenance and dependable workshop care — bringing professional auto service to your doorstep in Sahiwal.</p><div className="actions"><button className="primary" onClick={()=>go('contact')}>Book a Service <ArrowRight/></button><a href="tel:03016105452" className="ghost"><Phone size={17}/> 0301-6105452</a></div><div className="trust"><span><CheckCircle2/> Experienced Care</span><span><ShieldCheck/> Quality Service</span><span><Clock3/> Customer First</span></div></div><div className="hero-card"><small>CH AUTO WORKSHOP</small><strong>Precision<br/>meets care.</strong><span>Engine • Electrical • Maintenance</span></div></section>
<section className="marquee"><div>ENGINE DIAGNOSTICS • OIL CHANGE • BRAKES • BATTERY • SUSPENSION • ENGINE OVERHAUL • </div></section>
<section id="services" className="section"><div className="section-head reveal"><div><span className="eyebrow">WHAT WE DO</span><h2>Complete care for<br/><em>your vehicle.</em></h2></div><p>From a quick inspection to major engine work, our services are designed around safety, performance and long-term reliability.</p></div><div className="service-grid">{services.map(([title,desc,Icon],i)=><article className="service reveal" key={title}><div className="service-num">0{i+1}</div><div className="icon"><Icon/></div><h3>{title}</h3><p>{desc}</p><a href="#contact" onClick={()=>go('contact')}>Explore service <ArrowRight size={15}/></a></article>)}</div></section>
<section id="about" className="split section dark"><div className="visual reveal"><div className="garage-card"><span>WORKSHOP STANDARD</span><b>01</b><p>Inspect.<br/>Diagnose.<br/>Repair.</p></div><div className="ring r1"/><div className="ring r2"/></div><div className="about-copy reveal"><span className="eyebrow">ABOUT CH AUTO</span><h2>Local roots.<br/><em>Professional standards.</em></h2><p>CH Auto Workshop is built around a simple promise: treat every vehicle with attention and every customer with respect. Our approach combines practical workshop experience with modern diagnostic thinking.</p><p>Whether your car needs routine maintenance or a deeper repair, we focus on finding the real issue — not just the symptom.</p><div className="stats"><div><b>10+</b><span>Core Services</span></div><div><b>4-W</b><span>Brake Care</span></div><div><b>100%</b><span>Care Focus</span></div></div></div></section>
<section id="why" className="section"><div className="section-head reveal"><div><span className="eyebrow">WHY CHOOSE US</span><h2>Service that feels<br/><em>straightforward.</em></h2></div><p>No confusing workshop talk. We inspect the vehicle, explain what matters and help you make the right maintenance decision.</p></div><div className="why-grid"><div className="why-main reveal"><span>01</span><h3>Diagnostic-first thinking</h3><p>We start with inspection and diagnosis before recommending repair. That means less guesswork and more confidence.</p></div><div className="why-item reveal"><ShieldCheck/><h3>Safety focused</h3><p>Brakes, steering, suspension and battery checks are treated as essential, not optional.</p></div><div className="why-item reveal"><Gauge/><h3>Performance care</h3><p>Engine, throttle, injectors and ignition systems get practical attention for smoother running.</p></div><div className="why-item reveal"><Wrench/><h3>Maintenance mindset</h3><p>Regular oil, filter and inspection work can help avoid expensive surprises later.</p></div></div></section>
<section id="gallery" className="section workshop"><div className="section-head reveal"><div><span className="eyebrow">THE WORKSHOP</span><h2>A modern feel.<br/><em>Hands-on service.</em></h2></div></div><div className="gallery-grid"><div className="photo p1 reveal"><span>ENGINE CARE</span></div><div className="photo p2 reveal"><span>DIAGNOSTICS</span></div><div className="photo p3 reveal"><span>MAINTENANCE</span></div><div className="photo p4 reveal"><span>PRECISION WORK</span></div></div></section>
<section className="banner reveal"><div><span className="eyebrow">YOUR CAR DESERVES BETTER</span><h2>Keep moving.<br/><em>We'll handle the details.</em></h2></div><button className="primary" onClick={()=>go('contact')}>Talk to the Workshop <ArrowRight/></button></section>
<section id="contact" className="contact section"><div className="contact-copy reveal"><span className="eyebrow">GET IN TOUCH</span><h2>Let's keep your<br/><em>car road-ready.</em></h2><p>Call the workshop for service enquiries, maintenance guidance or to discuss your vehicle.</p><div className="contact-list"><a href="tel:03016105452"><Phone/><div><small>PHONE</small><b>0301-6105452</b></div></a><div><MapPin/><div><small>LOCATION</small><b>Madina Market, Shaheed Road, Sahiwal</b></div></div><div><Clock3/><div><small>WORKSHOP</small><b>Service by appointment / enquiry</b></div></div></div></div><form className="form reveal" onSubmit={e=>{e.preventDefault();window.location.href='tel:03016105452'}}><label>Your name<input required placeholder="Your name"/></label><label>Vehicle / service<input placeholder="e.g. Engine diagnostics"/></label><label>Message<textarea rows="5" placeholder="Tell us what your car needs..."/></label><button className="primary" type="submit">Send Enquiry <ArrowRight/></button><small>Submitting this form opens the workshop phone contact. No data is stored on this website.</small></form></section>
<footer><div className="brand"><span>CH</span><div><b>CH AUTO</b><small>WORKSHOP</small></div></div><p>© 2026 CH Auto Workshop. Sahiwal, Pakistan.</p><button onClick={()=>go('home')}>Back to top ↑</button></footer>
</div>}
createRoot(document.getElementById('root')).render(<App/>);