import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ArrowRight,Phone,MapPin,Wrench,Gauge,ShieldCheck,BatteryCharging,CarFront,Menu,X,CheckCircle2,Clock3,Sparkles} from 'lucide-react';
import './styles.css';
import './experience.css';
import './visual-polish.css';
import RealisticBMW from './RealisticBMW.jsx';
gsap.registerPlugin(ScrollTrigger);

const services=[['Engine Diagnostics','Computer scanning, fault tracing and accurate engine health checks.',Gauge],['Oil Change & Maintenance','Quality oil service, filters, fluids and preventive maintenance.',Wrench],['Catalytic Converter Service','Inspection, cleaning and troubleshooting for exhaust performance.',CarFront],['Suspension & Steering Check','Brake, suspension, wheel and steering safety inspection.',ShieldCheck],['Battery Inspection','Battery health, charging system and starting diagnostics.',BatteryCharging],['Engine Overhauling','Detailed engine repair and overhaul work with careful inspection.',Wrench],['Throttle Body Cleaning','Restore smoother throttle response and better idle performance.',Gauge],['Injector Cleaning','Fuel injector cleaning for efficient combustion and performance.',Sparkles],['Spark Plug Cleaning','Inspection and cleaning to support reliable ignition.',Sparkles],['4-Wheel Brake Service','Brake inspection, cleaning and maintenance for confident stopping.',ShieldCheck]];

function App(){
 const[open,setOpen]=useState(false);const root=useRef();
 useEffect(()=>{try{gsap.fromTo('.hero-copy > *',{y:35,opacity:0},{y:0,opacity:1,duration:1,stagger:.1,ease:'power3.out'});gsap.fromTo('.bmw-experience',{y:45,opacity:0,scale:.97},{y:0,opacity:1,scale:1,duration:1.25,ease:'power4.out',delay:.15});gsap.utils.toArray('.reveal').forEach(el=>gsap.fromTo(el,{y:45,opacity:0},{y:0,opacity:1,duration:.8,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 84%'}}));}catch(e){console.warn('Motion fallback:',e)}return()=>{try{ScrollTrigger.getAll().forEach(t=>t.kill())}catch(e){}}},[]);
 const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setOpen(false)};
 return <div ref={root}>
  <header className="nav"><div className="brand" onClick={()=>go('home')}><span>CH</span><div><b>CH AUTO</b><small>WORKSHOP</small></div></div><button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'show':''}><button onClick={()=>go('home')}>Home</button><button onClick={()=>go('services')}>Services</button><button onClick={()=>go('about')}>About</button><button onClick={()=>go('why')}>Why Us</button><button onClick={()=>go('gallery')}>Workshop</button><button className="nav-cta" onClick={()=>go('contact')}>Contact <ArrowRight size={16}/></button></nav></header>
  <section id="home" className="hero car-hero"><div className="hero-ambient"/><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow">SAHIWAL • PAKISTAN <span>EST. AUTO CARE</span></div><h1>Your car.<br/><em>Our precision.</em></h1><p>Modern diagnostics, honest maintenance and workshop care built for the roads of Sahiwal.</p><div className="actions"><button className="primary" onClick={()=>go('contact')}>Book a Service <ArrowRight/></button><a href="tel:03016105452" className="ghost"><Phone size={17}/> 0301-6105452</a></div><div className="trust"><span><CheckCircle2/> Experienced Care</span><span><ShieldCheck/> Quality Service</span><span><Clock3/> Customer First</span></div></div><RealisticBMW/></section>
  <section className="marquee"><div>ENGINE DIAGNOSTICS • OIL CHANGE • BRAKES • BATTERY • SUSPENSION • ENGINE OVERHAUL • THROTTLE • INJECTORS • </div></section>
  <section id="services" className="section services-new"><div className="section-head reveal"><div><span className="eyebrow">01 / SERVICES</span><h2>Built around<br/><em>your drive.</em></h2></div><p>From a warning light to a complete overhaul, CH Auto combines practical workshop experience with modern diagnostic thinking.</p></div><div className="service-grid">{services.map(([title,desc,Icon],i)=><article className="service reveal" key={title}><div className="service-num">0{i+1}</div><div className="icon"><Icon/></div><h3>{title}</h3><p>{desc}</p><a href="#contact" onClick={()=>go('contact')}>Explore service <ArrowRight size={15}/></a></article>)}</div></section>
  <section id="about" className="split section dark"><div className="visual reveal"><div className="garage-card"><span>WORKSHOP STANDARD</span><b>CH</b><p>Inspect.<br/>Diagnose.<br/>Repair.</p></div><div className="ring r1"/><div className="ring r2"/></div><div className="about-copy reveal"><span className="eyebrow">02 / ABOUT CH AUTO</span><h2>Local roots.<br/><em>Professional standards.</em></h2><p>CH Auto Workshop is built around a simple promise: treat every vehicle with attention and every customer with respect.</p><p>Whether your car needs routine maintenance or a deeper repair, we focus on finding the real issue — not just the symptom.</p><div className="stats"><div><b>10+</b><span>Core Services</span></div><div><b>4-W</b><span>Brake Care</span></div><div><b>360°</b><span>Vehicle Focus</span></div></div></div></section>
  <section id="why" className="section why-section"><div className="section-head reveal"><div><span className="eyebrow">03 / WHY US</span><h2>Less noise.<br/><em>More confidence.</em></h2></div><p>No confusing workshop talk. We inspect the vehicle, explain what matters and help you make the right maintenance decision.</p></div><div className="why-grid"><div className="why-main reveal"><span>01</span><h3>Diagnostic-first thinking.</h3><p>Inspection comes before recommendations. Less guesswork means a clearer repair path.</p></div><div className="why-item reveal"><ShieldCheck/><h3>Safety focused</h3><p>Brakes, steering, suspension and battery checks are treated as essential.</p></div><div className="why-item reveal"><Gauge/><h3>Performance care</h3><p>Engine, throttle, injectors and ignition systems get practical attention.</p></div><div className="why-item reveal"><Wrench/><h3>Maintenance mindset</h3><p>Regular service helps keep expensive surprises away.</p></div></div></section>
  <section id="gallery" className="section workshop"><div className="section-head reveal"><div><span className="eyebrow">04 / WORKSHOP</span><h2>Inside the<br/><em>garage.</em></h2></div><p>Machines, tools and careful hands — presented as a visual journey rather than a static gallery.</p></div><div className="gallery-grid"><div className="photo p1 reveal"><span>ENGINE CARE / 01</span></div><div className="photo p2 reveal"><span>DIAGNOSTICS / 02</span></div><div className="photo p3 reveal"><span>MAINTENANCE / 03</span></div><div className="photo p4 reveal"><span>PRECISION WORK / 04</span></div></div></section>
  <section className="banner reveal"><div><span className="eyebrow">YOUR CAR DESERVES BETTER</span><h2>Keep moving.<br/><em>We'll handle the details.</em></h2></div><button className="primary" onClick={()=>go('contact')}>Talk to the Workshop <ArrowRight/></button></section>
  <section id="contact" className="contact section"><div className="contact-copy reveal"><span className="eyebrow">05 / CONTACT</span><h2>Let's keep your<br/><em>car road-ready.</em></h2><p>Call the workshop for service enquiries, maintenance guidance or to discuss your vehicle.</p><div className="contact-list"><a href="tel:03016105452"><Phone/><div><small>PHONE</small><b>0301-6105452</b></div></a><div><MapPin/><div><small>LOCATION</small><b>Madina Market, Shaheed Road, Sahiwal</b></div></div><div><Clock3/><div><small>WORKSHOP</small><b>Service by appointment / enquiry</b></div></div></div></div><form className="form reveal" onSubmit={e=>{e.preventDefault();window.location.href='tel:03016105452'}}><label>Your name<input required placeholder="Your name"/></label><label>Vehicle / service<input placeholder="e.g. Engine diagnostics"/></label><label>Message<textarea rows="5" placeholder="Tell us what your car needs..."/></label><button className="primary" type="submit">Send Enquiry <ArrowRight/></button><small>Submitting this form opens the workshop phone contact. No data is stored on this website.</small></form></section>
  <footer><div className="brand"><span>CH</span><div><b>CH AUTO</b><small>WORKSHOP</small></div></div><p>© 2026 CH Auto Workshop. Sahiwal, Pakistan.</p><p className="model-credit">BMW M4 3D model: SRT Performance • CC BY 4.0</p><button onClick={()=>go('home')}>Back to top ↑</button></footer>
 </div>
}
window.addEventListener('error',e=>console.warn('CH Auto client error:',e.error||e.message));window.addEventListener('unhandledrejection',e=>console.warn('CH Auto async error:',e.reason));createRoot(document.getElementById('root')).render(<App/>);
