import React from 'react';
import {ArrowRight,Phone,MapPin,Wrench,Gauge,ShieldCheck,BatteryCharging,CarFront,Clock3,CheckCircle2,ChevronDown,Navigation,Settings2,Zap,CircleCheck,ClipboardCheck,Search,HeartHandshake} from 'lucide-react';
import RealisticBMW from './RealisticBMW.jsx';
import './pages.css';

const LOGO='/ch-auto-logo-exact.svg';
const services=[
 ['Engine Diagnostics','Computer scanning, warning-light diagnosis, fault tracing and practical repair guidance.',Gauge],
 ['Oil Change & Maintenance','Oil, filters, fluids and routine checks designed around the condition of your vehicle.',Wrench],
 ['Brake Service','Inspection and maintenance of pads, discs, calipers and braking components.',ShieldCheck],
 ['Battery & Starting','Battery health, charging-system and starting checks before you replace parts unnecessarily.',BatteryCharging],
 ['Suspension & Steering','Checks for worn components, steering feel, ride quality and safety-critical movement.',CarFront],
 ['Engine Overhauling','Detailed engine inspection, repair planning and overhaul work when a deeper fix is required.',Settings2],
 ['Throttle & Injectors','Cleaning and inspection for smoother response, idle quality and efficient combustion.',Zap],
 ['Catalytic Converter','Exhaust inspection, troubleshooting and service guidance for performance and emissions concerns.',Gauge]
];
const nav=[['Home','/'],['Services','/services/'],['About','/about/'],['Workshop','/workshop/'],['Contact','/contact/']];

export function navigate(path){window.history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'instant'});}
function Header(){return <header className="nav"><a className="brand" href="/" onClick={e=>{e.preventDefault();navigate('/')}}><img className="site-logo" src={LOGO} alt="Chaudhry Auto Workshop" width="178" height="60"/></a><nav>{nav.map(([label,path])=><a key={path} href={path} className={location.pathname===path?'active':''} onClick={e=>{e.preventDefault();navigate(path)}}>{label}</a>)}</nav><a className="nav-call" href="tel:03016105452"><Phone size={16}/> Call Workshop</a></header>}
function Footer(){return <footer className="site-footer"><div><img className="footer-logo" src={LOGO} alt="Chaudhry Auto Workshop" width="160" height="58"/><p>Sahiwal-built automotive care with a diagnostic-first mindset.</p></div><div><b>Explore</b><a href="/services/" onClick={e=>{e.preventDefault();navigate('/services/')}}>Services</a><a href="/about/" onClick={e=>{e.preventDefault();navigate('/about/')}}>About CH Auto</a><a href="/workshop/" onClick={e=>{e.preventDefault();navigate('/workshop/')}}>Workshop</a></div><div><b>Contact</b><a href="tel:03016105452">0301-6105452</a><span>Bahir Wala Adda, Madina Market, Tufail Shaheed Rd, Sahiwal</span></div><div><b>Start here</b><a className="footer-cta" href="/contact/" onClick={e=>{e.preventDefault();navigate('/contact/')}}>Request a service <ArrowRight size={15}/></a></div><small className="copyright">© 2026 CH Auto Workshop · Sahiwal, Pakistan · BMW M4 3D model: SRT Performance • CC BY 4.0</small></footer>}
function Shell({children,kicker,title,lead}){return <><Header/><main><section className="page-hero"><div><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{lead}</p></div><div className="page-orbit"><span>CH</span><i></i><i></i><i></i></div></section>{children}</main><Footer/></>}
function CTA({title='Ready when your car is?',text='Tell us what the vehicle is doing. We will help you choose the right next step.',label='Talk to the workshop'}){return <section className="page-cta"><div><span className="eyebrow">CH AUTO / SAHIWAL</span><h2>{title}</h2><p>{text}</p></div><a className="primary" href="/contact/" onClick={e=>{e.preventDefault();navigate('/contact/')}}>{label}<ArrowRight/></a></section>}

export function HomePage(){return <><Header/><main><section className="hero car-hero home-hero"><div className="hero-ambient"/><div className="hero-grid"/><RealisticBMW/><div className="hero-copy"><div className="eyebrow">SAHIWAL • PAKISTAN <span>EST. AUTO CARE</span></div><h1>Your car.<br/><em>Our precision.</em></h1><p>Modern diagnostics, honest maintenance and workshop care built for the roads of Sahiwal.</p><div className="actions"><a className="primary" href="/contact/" onClick={e=>{e.preventDefault();navigate('/contact/')}}>Request a Service <ArrowRight/></a><a href="tel:03016105452" className="ghost"><Phone size={17}/> 0301-6105452</a></div><div className="trust"><span><CheckCircle2/> Diagnostic-first</span><span><ShieldCheck/> Safety focused</span><span><Clock3/> Local workshop</span></div></div></section><section className="home-intro"><div><span className="eyebrow">01 / THE CH AUTO METHOD</span><h2>A workshop website should feel like a workshop: <em>clear, capable, considered.</em></h2></div><p>We have separated the experience into dedicated pages so visitors can explore services, understand the workshop philosophy and find practical contact information without one endless scroll.</p></section><section className="home-cards"><a href="/services/" onClick={e=>{e.preventDefault();navigate('/services/')}}><span>01</span><Gauge/><h3>Services with context</h3><p>Explore what each service is for, what we inspect and what a sensible next step looks like.</p><b>Explore services <ArrowRight/></b></a><a href="/about/" onClick={e=>{e.preventDefault();navigate('/about/')}}><span>02</span><HeartHandshake/><h3>People & principles</h3><p>Understand the diagnostic-first approach, communication standards and care philosophy behind CH Auto.</p><b>Meet CH Auto <ArrowRight/></b></a><a href="/workshop/" onClick={e=>{e.preventDefault();navigate('/workshop/')}}><span>03</span><Settings2/><h3>Inside the workshop</h3><p>A deeper look at inspection, service flow, maintenance thinking and the road-ready checklist.</p><b>Enter the workshop <ArrowRight/></b></a></section><CTA title="Need a mechanic, not a maze?" text="Go straight to the service page that matches your problem, or call the workshop in Sahiwal."/></main><Footer/></>}

export function ServicesPage(){return <Shell kicker="01 / SERVICES" title={<>Service depth for <em>real-world driving.</em></>} lead="From a warning light to a full engine overhaul, explore the work CH Auto is built around — with clear explanations instead of a wall of jargon."><section className="service-list">{services.map(([name,desc,Icon],i)=><article className="service-detail" key={name}><div className="service-index">0{i+1}</div><div className="service-icon"><Icon/></div><div><span className="eyebrow">SYSTEM {String(i+1).padStart(2,'0')}</span><h2>{name}</h2><p>{desc}</p><div className="service-points"><span><CircleCheck/> Visual inspection</span><span><CircleCheck/> Diagnostic reasoning</span><span><CircleCheck/> Repair guidance</span></div></div><a href="/contact/" onClick={e=>{e.preventDefault();navigate('/contact/')}}>Discuss this service <ArrowRight/></a></article>)}</section><section className="process"><div className="section-head"><div><span className="eyebrow">HOW WE WORK</span><h2>Inspect first.<br/><em>Repair with purpose.</em></h2></div><p>A professional service experience is more than replacing a part. The workflow should make the problem understandable before the repair becomes expensive.</p></div><div className="process-grid"><article><Search/><span>01</span><h3>Listen & inspect</h3><p>We start with the driver's symptoms, vehicle context and visible condition.</p></article><article><Gauge/><span>02</span><h3>Diagnose</h3><p>Checks and scanning help narrow the problem instead of guessing at parts.</p></article><article><ClipboardCheck/><span>03</span><h3>Explain</h3><p>The customer should understand what matters, what can wait and why.</p></article><article><Wrench/><span>04</span><h3>Service</h3><p>The repair or maintenance work follows the diagnosis and agreed direction.</p></article></div></section><section className="service-guide"><div><span className="eyebrow">NOT SURE WHERE TO START?</span><h2>Describe the symptom.<br/><em>We can start there.</em></h2></div><div className="guide-grid"><div><b>Warning light</b><p>Bring the exact dashboard message or tell us when it appears.</p></div><div><b>Noise / vibration</b><p>Note when it happens: braking, turning, acceleration or rough roads.</p></div><div><b>Performance drop</b><p>Tell us what changed: power, idle, fuel use, starting or response.</p></div><div><b>Routine maintenance</b><p>Share the vehicle and last known service details if available.</p></div></div></section><CTA title="Find the right next step."/></Shell>}

export function AboutPage(){return <Shell kicker="02 / ABOUT CH AUTO" title={<>Local roots.<br/><em>Professional standards.</em></>} lead="CH Auto Workshop is designed around a simple idea: good automotive care should reduce uncertainty, not add to it."><section className="about-story"><div className="story-visual"><div className="garage-card"><span>WORKSHOP STANDARD</span><b>CH</b><p>Inspect.<br/>Diagnose.<br/>Repair.</p></div><div className="ring r1"/><div className="ring r2"/></div><div className="story-copy"><span className="eyebrow">THE PHILOSOPHY</span><h2>Less guessing.<br/><em>More understanding.</em></h2><p>Drivers do not need a lecture full of technical words. They need someone to identify what is happening, explain the important part and make the next decision easier.</p><p>That is why the CH Auto experience is built around diagnostics, maintenance discipline and straightforward communication.</p><div className="principles"><div><b>01</b><h3>Diagnose before replacing</h3><p>Use evidence to narrow the problem before recommending parts.</p></div><div><b>02</b><h3>Safety before convenience</h3><p>Brakes, steering, suspension and starting systems deserve careful attention.</p></div><div><b>03</b><h3>Explain the why</h3><p>A customer should know what is being done and why it matters.</p></div></div></div></section><section className="values"><div><span className="eyebrow">WHAT GOOD SERVICE FEELS LIKE</span><h2>A better workshop experience is <em>quietly detailed.</em></h2></div><div className="value-grid"><article><Navigation/><h3>Local</h3><p>Built for drivers in Sahiwal, with location and contact details kept easy to find.</p></article><article><ShieldCheck/><h3>Safety-minded</h3><p>Critical systems are treated as part of a complete vehicle, not isolated parts.</p></article><article><Zap/><h3>Modern</h3><p>Diagnostic thinking and a contemporary digital experience belong together.</p></article><article><HeartHandshake/><h3>Human</h3><p>Clear language and respectful communication are part of the service.</p></article></div></section><section className="timeline"><span className="eyebrow">THE CUSTOMER JOURNEY</span><div><b>01</b><h3>Before the visit</h3><p>Find the service, call the workshop and describe the issue.</p></div><div><b>02</b><h3>At the workshop</h3><p>Inspection and diagnosis turn symptoms into a clearer repair direction.</p></div><div><b>03</b><h3>After service</h3><p>Know what was addressed and what maintenance deserves attention next.</p></div></section><CTA title="Want to talk to CH Auto?" text="Call directly or send a service enquiry with your vehicle problem."/></Shell>}

export function WorkshopPage(){return <Shell kicker="03 / WORKSHOP" title={<>Inside the garage.<br/><em>Behind every road-ready car.</em></>} lead="A long-form workshop guide for drivers who want to understand what happens between the warning light and the finished repair."><section className="workshop-hero"><div className="workshop-panel"><span className="eyebrow">WORKSHOP FLOW / 360° VIEW</span><h2>From symptom to <em>solution.</em></h2><p>The most useful service journey is not mysterious. It is a sequence: listen, inspect, test, explain, service and check.</p><div className="flow-line"><span>SYMPTOM</span><i></i><span>DIAGNOSIS</span><i></i><span>SERVICE</span><i></i><span>ROAD READY</span></div></div><div className="workshop-stat"><b>360°</b><span>vehicle focus</span><small>Engine · brakes · battery · steering · suspension · maintenance</small></div></section><section className="deep-sections"><article><span>01</span><div><h2>The warning light is a clue, not a diagnosis.</h2><p>A dashboard light tells you that a system has detected something outside its expected range. The useful question is what caused it. That is why scanning, symptom history and inspection should work together.</p><p>For drivers, this means fewer assumptions and a better chance of addressing the underlying issue instead of repeatedly treating a symptom.</p></div></article><article><span>02</span><div><h2>Maintenance is cheaper when it is intentional.</h2><p>Oil, filters, fluids, battery health, brakes and suspension checks are not glamorous, but they are where small observations can prevent larger surprises. A maintenance visit should leave you knowing what is healthy, what needs attention and what can be monitored.</p></div></article><article><span>03</span><div><h2>Performance is a system.</h2><p>Throttle response, injectors, ignition, air, fuel and engine management interact. When a car feels slower, rougher or harder to start, looking at the whole system creates a better diagnostic path than swapping random components.</p></div></article></section><section className="road-ready"><div><span className="eyebrow">ROAD-READY CHECK</span><h2>Before the keys go back, the details matter.</h2></div><div className="check-grid"><span><CheckCircle2/> Braking feel</span><span><CheckCircle2/> Starting response</span><span><CheckCircle2/> Fluid condition</span><span><CheckCircle2/> Warning lights</span><span><CheckCircle2/> Steering / suspension</span><span><CheckCircle2/> Customer explanation</span></div></section><CTA title="Bring us the symptom." text="You do not need to know the mechanical name for the problem. Tell us what the car is doing."/></Shell>}

export function ContactPage(){return <Shell kicker="04 / CONTACT" title={<>Let's keep your<br/><em>car road-ready.</em></>} lead="Use the phone for the fastest response, or send a short enquiry so the workshop knows what your vehicle needs."><section className="contact-page"><div className="contact-card"><span className="eyebrow">DIRECT LINE</span><h2>0301-6105452</h2><a className="primary" href="tel:03016105452"><Phone/> Call CH Auto <ArrowRight/></a><div className="contact-meta"><div><MapPin/><span><b>Location</b>Bahir Wala Adda, Madina Market, Tufail Shaheed Rd, Sahiwal</span></div><div><Clock3/><span><b>Workshop</b>Service by appointment / enquiry</span></div></div></div><form className="enquiry-form" onSubmit={e=>{e.preventDefault();window.location.href='tel:03016105452'}}><span className="eyebrow">SERVICE ENQUIRY</span><h2>Tell us what the car is doing.</h2><label>Your name<input required placeholder="Your name"/></label><label>Vehicle / model<input placeholder="e.g. BMW / Toyota / Honda"/></label><label>What needs attention?<textarea required rows="6" placeholder="Warning light, noise, service due, starting issue..."></textarea></label><button className="primary" type="submit">Send enquiry <ArrowRight/></button><small>This website does not store the form. Submitting opens the workshop phone contact.</small></form></section><section className="contact-strip"><div><b>Bring the symptom.</b><span>You do not need the technical name.</span></div><div><b>Bring the vehicle details.</b><span>Model and the issue timeline help.</span></div><div><b>Bring your questions.</b><span>Clear explanations are part of good service.</span></div></section></Shell>}

export function SiteRouter(){const[path,setPath]=React.useState(location.pathname);React.useEffect(()=>{const f=()=>setPath(location.pathname);addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);if(path.startsWith('/services'))return <ServicesPage/>;if(path.startsWith('/about'))return <AboutPage/>;if(path.startsWith('/workshop'))return <WorkshopPage/>;if(path.startsWith('/contact'))return <ContactPage/>;return <HomePage/>;}
